name: Deploy Storybook Firebase Hosting - manual
'on': [workflow_dispatch]
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci --legacy-peer-deps && npm run sb-build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EASY_SAAS_PLATFORM }}'
          channelId: live
          projectId: easy-saas-platform
          target: easysaas-storybook
